### ISSUE TITLE
Search Filters not actually being applied

### ISSUE THREAD

**Issue by EricNeville** [AnthonyBloomer/daftlistings#103] opened 2021-04-02 16:54 UTC
I've been trying to use the module from the dev version and it seems that my search parameters are not actually being applied. My search is as below:

```
from daftlistings.daft import Daft
from daftlistings.enums import SearchType, PropertyType
from daftlistings.location import Location

daft = Daft()
daft.set_search_type(SearchType.RESIDENTIAL_RENT)
daft.set_property_type(PropertyType.APARTMENT)
daft.set_location(Location.GRAND_CANAL_DOCK_DUBLIN)
daft.set_location(Location.IFSC_DUBLIN)
daft.set_min_beds(2)
daft.set_max_beds(2)
daft.set_min_price(1500)
daft.set_max_price(3000)
```

and the issue can be seen clearly by adding:

```
import pandas as pd

cols = ['title', 'price', 'point', 'seoFriendlyPath', 'category', 'propertyType', 'numBedrooms']
data = [[vars(item)["_result"][col] for col in cols] for item in listings]
data = pd.DataFrame(data, columns = ['Title', 'Price', 'Coordinates', 'Link', 'Type', 'Property', 'Beds'])

print('\nSearch Types:', data.Type.unique())
print('\nProperty Types:', data.Property.unique())
print('\nNumbers of Beds:', data.Beds.unique())
```

The result seems to be including rental and sale properties, houses and apartments, any range of prices and number of bedrooms. From looking at the other examples in the repo I can't see an issue with my implementation.

**Comment by sdfordham** [comment] 2021-04-02 17:28
This property type bug is caused by
https://github.com/AnthonyBloomer/daftlistings/blob/a94d2112d8375a90b9be8d1bb16a3cae9b7e95fb/daftlistings/enums.py#L6
it should be `"residential-to-rent"`.

I'm not sure about the issue with the bed count... I compared the payload generated with `daft._make_payload()` with the payload generated on the webpage and they are identical. There must be further logic in the front-end that does another filter. It may be necessary to add extra code for this.

**Comment by sdfordham** [comment] 2021-04-02 18:10
Issue with price/bedroom caused by this
https://github.com/AnthonyBloomer/daftlistings/blob/a94d2112d8375a90b9be8d1bb16a3cae9b7e95fb/daftlistings/daft.py#L158
`"range"` should be `"ranges"`.

**Comment by sdfordham** [comment] 2021-04-02 18:28
@EricNeville This is all fixed now.
````python
from daftlistings.daft import Daft
from daftlistings.enums import SearchType, PropertyType
from daftlistings.location import Location

daft = Daft()
daft.set_search_type(SearchType.RESIDENTIAL_RENT)
daft.set_property_type(PropertyType.APARTMENT)
daft.set_location(Location.GRAND_CANAL_DOCK_DUBLIN)
daft.set_location(Location.IFSC_DUBLIN)
daft.set_min_beds(2)
daft.set_max_beds(2)
daft.set_min_price(1500)
daft.set_max_price(3000)

listings = daft.search()

prices = [l.abbreviated_price for l in listings]
prices = [int(p.strip('€').replace(',', '')) for p in prices]
prices = any([p > 3000 or p < 1500 for p in prices])
print('Any prices out of range:', prices)

beds = any(['2' not in l.bedrooms for l in listings])
print('Any without 2 beds:', beds)
````
Output:
````console
Got 122 results.
Any prices out of range: False
Any without 2 beds: False
````
Until the pull request is approved you should use [this branch](https://github.com/AnthonyBloomer/daftlistings/tree/search-filter-not-applied-issue-103).

**Closed** 2021-04-02 20:00 UTC
